---
title: "Fertile soil for best practises"
description-meta: ""
pagetitle: "Fertile soil for best practises"
---

Welcome at the Fertile-soil research project which is planned by Keke Merz to be executed in Germany and Japan.

# Context

The recent heat wave in 2025 in Japan with repeatedly new temperature records makes it clear that climate adaption measures must be broadly introduced to help dampen the threats from climate change. Here, the sector of transport plays a major role with its high emissions (CO2, NOx, noise) and integral impact of the shape, streets and citizen health in our cities. The ongoing urban mobility transformation (UMT) re-envisions the street space not only as transitional space but as public space for human activity. Cities like Paris show that such a change is possible: Paris improved its air quality and quality of live focusing on multi-modal modes (cycling, walking, strong public transport) by extending cycling infrastructure and bike sharing \[3\]. So how can these transformation be achieved with high accepatability by politics and the public? Which goals are actually targeted and which constraints need to be considered? Transformational approaches must be country- and city-specific, considering local rules, laws, habits, and history (localisation). To plant best practises, we must first understand the ”soil”, meaning the specific targets and constraints of a city and country. With this knowledge, we can build robust and adaptable frameworks and choose fitting methods for the urban transformation to be implemented (see Figure @fig-methodology). Comparisons between countries are an especially suited method to uncover differences and similarities which might otherwise stay invisible as status quo \[2\].

# Objective

The objective of this study is to compile an academic overview on the similarities and differences of targets and constraints for the urban mobility transition in Japan and Germany. Depending on data availability, specific regions will be targeted, e.g., Munich and (a district of) Tokyo.

# Research question 

The central research question that is to be tackled in this study is: What are context-specific differences and similarities in targets and constraints that influence the possible adaption of best practises in the UMT context towards climate change adaption with the examples of Japan and Germany?

# Contribution

The contribution of this study to the research area will fill the gap of understanding local conditions in the written academic discourse and will lead to deeper insights on how the local context affect the success and suitability of climate adaption measures in UMT (e.g., improving cycling infrastructure).
